# Use Maven image to build the JAR
FROM maven:latest AS build
WORKDIR /app

# Copy the source code into the container
COPY . .

# Build the JAR file
RUN mvn clean package

# Use a lightweight JDK image to run the application
FROM openjdk:17-slim
WORKDIR /app

# Copy the built JAR from the previous stage
COPY --from=build /app/target/journex-0.0.1-SNAPSHOT.jar .

# Run the application
CMD ["java", "-jar", "journex-0.0.1-SNAPSHOT.jar"]