FROM maven:latest AS build
WORKDIR /app

COPY . .

RUN mvn clean package

FROM openjdk:17-slim
WORKDIR /app

COPY --from=build /app/target/journex-0.0.1-SNAPSHOT.jar .

CMD ["java", "-jar", "journex-0.0.1-SNAPSHOT.jar"]