server.port=9090
spring.application.name=Journex
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/journex_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Mohajer123456}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.messages.basename=JournexBundle
jwt.secret=JournexSecretKeyForJwtAuthenticationJournex
jwt.expiration=86400000
jwt.blacklist=jwt:blacklist
jwt.loginAttemptPrefix=login:attempts:
jwt.maxLoginAttempts=5
jwt.lockoutDurationMinutes=15
frontend.url=http://localhost:5173
#spring.ai.vectorstore.redis.initialize-schema=true
#spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.multimodal.model=llava:7b
#spring.ai.ollama.embedding.model=all-minilm:22m
#spring.ai.ollama.embedding.enabled=false
#spring.ai.openai.base_url=https://api.groq.com/openai
#spring.ai.openai.api-key=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
#spring.ai.openai.chat.options.model=gemma2-9b-it
#spring.ai.openai.image.options.model=llama-3.2-11b-vision-preview
#spring.ai.openai.audio.transcription.options.model=whisper-large-v3
#spring.ai.openai.embedding.options.model=${spring.ai.ollama.embedding.model}
#spring.ai.openai.embedding.base-url=${spring.ai.ollama.base-url}
#spring.ai.openai.embedding.enabled=true
#spring.ai.openai.chat.options.max-tokens=50000
